# Generated by Django 5.0.6 on 2024-06-10 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ModoUso',
            fields=[
                ('id_ModoUso', models.AutoField(db_column='idModoUso', primary_key=True, serialize=False)),
                ('ModoUso', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=20)),
                ('precio', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('colores', models.CharField(max_length=20)),
                ('creador', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=20)),
                ('id_ModoUso', models.ForeignKey(db_column='idModoUso', on_delete=django.db.models.deletion.CASCADE, to='nekoBeansWeb.modouso')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('id_genero', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='nekoBeansWeb.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=20)),
                ('contrasena_user', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=20)),                
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('id_genero', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='nekoBeansWeb.genero')),
            ],
        ),
    ]
