# Generated by Django 4.2.13 on 2024-07-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nekoBeansWeb', '0002_remove_envio_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='nickname',
            field=models.CharField(default='nouser', max_length=100),
            preserve_default=False,
        ),
    ]
