# Generated by Django 5.0.6 on 2024-06-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nekoBeansWeb', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='colores',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
