# Generated by Django 5.0.1 on 2024-06-10 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nekoBeansWeb', '0002_alter_usuario_contrasena_user_alter_usuario_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='user_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=15)),
                ('contrasena_user', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('image_cedula', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('id_genero', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='nekoBeansWeb.genero')),
            ],
        ),
    ]
