# Generated by Django 4.2.13 on 2024-06-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nekoBeansWeb', '0003_alter_trabajaconnosotros_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='tipo_modo_uso',
            field=models.IntegerField(choices=[(1, 'Broche'), (2, 'Colgante')], default=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_modo_uso',
            field=models.IntegerField(choices=[(1, 'Broche'), (2, 'Colgante')], default=1),
        ),
    ]
