# Generated by Django 4.2.13 on 2024-07-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nekoBeansWeb', '0003_envio_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='entrega',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Entregado!')], default=1),
        ),
    ]
