# Generated by Django 4.2.13 on 2024-07-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nekoBeansWeb', '0004_envio_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='entrega',
            field=models.IntegerField(choices=[(1, ' - Pendiente'), (2, ' - Entregado!')], default=1),
        ),
    ]
