# Generated by Django 4.2.13 on 2024-06-16 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nekoBeansWeb', '0004_alter_producto_colores_alter_producto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10)),
                ('tipo_solicitud', models.IntegerField(choices=[[1, 'consulta'], [2, 'reclamo'], [3, 'sugerencia'], [4, 'felicitaciones'], [5, 'pedido especial']])),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePlantilla', models.CharField(max_length=20)),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('descripcion', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('id_ModoUso', models.ForeignKey(db_column='idModoUso', on_delete=django.db.models.deletion.CASCADE, to='nekoBeansWeb.modouso')),
            ],
        ),
    ]
