# Generated by Django 4.2.13 on 2024-06-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nekoBeansWeb', '0005_contacto_plantilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tipo_solicitud',
            field=models.IntegerField(choices=[(1, 'Consulta'), (2, 'Reclamo'), (3, 'Sugerencia'), (4, 'Felicitaciones'), (5, 'Pedidos especiales')]),
        ),
    ]
