# Generated by Django 4.2.13 on 2024-07-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nekoBeansWeb', '0007_alter_envio_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='entrega',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Entregado!')], default=1),
        ),
        migrations.AlterField(
            model_name='envio',
            name='estado_pedido',
            field=models.IntegerField(choices=[(1, 'En espera'), (2, 'En construcción'), (3, 'Listo!')], default=1),
        ),
        migrations.AlterField(
            model_name='envio',
            name='forma_pago',
            field=models.IntegerField(choices=[(1, 'Efectivo'), (2, 'Trasferencia'), (3, 'Tarjeta')], default=1),
        ),
    ]
