# Generated by Django 5.0.1 on 2024-06-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nekoBeansWeb', '0007_trabajaconnosotros_remove_colaborador_id_genero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantilla',
            name='id_ModoUso',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id_ModoUso',
        ),
        migrations.AddField(
            model_name='plantilla',
            name='tipo_modo_uso',
            field=models.IntegerField(choices=[(1, 'broche'), (2, 'colgante'), (3, 'ambos')], default=1),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_modo_uso',
            field=models.IntegerField(choices=[(1, 'broche'), (2, 'colgante'), (3, 'ambos')], default=1),
        ),
        migrations.DeleteModel(
            name='ModoUso',
        ),
    ]
