# Generated by Django 5.0.7 on 2024-07-16 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nekoBeansWeb', '0007_alter_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user_verificado',
        ),
    ]
