# Generated by Django 4.2.13 on 2024-07-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nekoBeansWeb', '0010_alter_envio_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='entrega',
            field=models.IntegerField(choices=[(1, ' - Pendiente'), (2, ' - Entregado!')], default=1),
        ),
        migrations.AlterField(
            model_name='envio',
            name='estado_pedido',
            field=models.IntegerField(choices=[(1, 'En espera'), (2, 'En construccion'), (3, 'Listo!')], default=1),
        ),
        migrations.AlterField(
            model_name='envio',
            name='forma_pago',
            field=models.IntegerField(choices=[(1, 'Efectivo'), (2, 'trasferencia'), (3, 'tarjeta')], default=1),
        ),
    ]
