# Generated by Django 4.2.13 on 2024-07-16 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nekoBeansWeb', '0010_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='carrito',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='nekoBeansWeb.carrito'),
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
