# Generated by Django 4.2.13 on 2024-07-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nekoBeansWeb', '0011_alter_envio_entrega_alter_envio_estado_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='entrega',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Entregado!')], default=1),
        ),
    ]
