# Generated by Django 4.2.13 on 2024-07-16 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nekoBeansWeb', '0011_envio_carrito_delete_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='carrito',
        ),
    ]
