# Generated by Django 4.2.13 on 2024-07-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nekoBeansWeb', '0014_remove_envio_fecha_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='productos',
            field=models.TextField(default='No hay productos'),
            preserve_default=False,
        ),
    ]
